### ISSUE TITLE
Tag Text with Structural Framing Tags

### ISSUE THREAD

**Issue by thazell** [ksobon/archi-lab.net#2]
I've repeated this error three times and wondering if you have a solution.  I was using "TagText" and when I do it with a foundation tag it works, but if I do it with a structural framing tag my Revit crashes. Any thoughts?

**Comment by ksobon** [comment]
can you share a small sample so I can re-create? I am not sure what exactly you are doing.

**Comment by thazell** [comment]
As I make you a sample it look it might be a dynamo issue, not an issue with the tag Text.  I hadn't even connected the tag to the tagtext node.

Is this a corruption in my installation?
![image](https://cloud.githubusercontent.com/assets/14113080/25201777/eedad5be-2520-11e7-9a4d-7b7ba817d57b.png)

**Comment by ksobon** [comment]
So just placing that node on canvas is causing the crash?

**Comment by thazell** [comment]
The crash happened when I selected the tag as an element, not when I added the Tag.TagText onto the canvas
[SavedRecoveryFile.zip](https://github.com/ksobon/archi-lab.net/files/938358/SavedRecoveryFile.zip)

**Comment by thazell** [comment]
I'm not sure it's an Archi-Lab issue any more. I've recreated the issue without the TagText node.

**Comment by ksobon** [comment]
This can't be archi-lab issue since neither one of the nodes is from my package. 

![image](https://cloud.githubusercontent.com/assets/529781/25202255/b8682cdc-2522-11e7-8fd4-bf3fd9068f76.png)

**Comment by thazell** [comment]
https://github.com/DynamoDS/DynamoRevit/issues/1651
