### ISSUE TITLE
Warning: Warning.GetWarnings operation failed in Revit 2016 and 2017

### ISSUE THREAD

**Issue by alexberd** [ksobon/archi-lab.net#4]
Warning: Warning.GetWarnings operation failed in Revit 2016 and 2017. The following error appears.

> Warning: Warning.GetWarnings operation failed. 
> Method not found: 'System.Collections.Generic.IList`1<Autodesk.Revit.DB.FailureMessage> Autodesk.Revit.DB.Document.GetWarnings()'.

**Running the following**
Windows 10
Revit 2018
Dynamo Core 1.3.2.2480

**Comment by ksobon** [comment]
That functionality doesnt exist in R2017 and R2016. It will not work.
